CREATE TABLE table_name (
    Patient_Number VARCHAR(255) NOT NULL,
    Sadness VARCHAR(255) NOT NULL,
    Euphoric VARCHAR(255) NOT NULL,
    Exhausted VARCHAR(255) NOT NULL,
    Sleep_dissorder VARCHAR(255) NOT NULL,
    Mood_Swing VARCHAR(255) NOT NULL,
    Suicidal_thoughts VARCHAR(255) NOT NULL,
    Anorxia VARCHAR(255) NOT NULL,
    Authority_Respect VARCHAR(255) NOT NULL,
    Try_Explanation VARCHAR(255) NOT NULL,
    Aggressive_Response VARCHAR(255) NOT NULL,
    Ignore_Move_On VARCHAR(255) NOT NULL,
    Nervous_Break_down VARCHAR(255) NOT NULL,
    Admit_Mistakes VARCHAR(255) NOT NULL,
    Overthinking VARCHAR(255) NOT NULL,
    Sexual_Activity VARCHAR(255) NOT NULL,
    Concentration VARCHAR(255) NOT NULL,
    Optimisim VARCHAR(255) NOT NULL,
    Expert_Diagnose VARCHAR(255) NOT NULL,
    PRIMARY KEY (Patient_Number)
);